name: Deploy to Firebase

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CI: false
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 19.3.0
        check-latest: true

    - name: Install dependencies
      run: npm install -g npm@9.2.0

    - name: Install project dependencies
      run: npm install

    - name: Build
      run: npm run build

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Deploy to Firebase
      uses: w9jds/firebase-action@v2
      with:
        args: deploy --token="${{ secrets.FIREBASE_TOKEN }}"
      env:
        CI: false  # Disable CI environment variable to bypass ESLint checks temporarily
        FIREBASE_CLI_DEPLOY: 1
