name: Firebase Function Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js and Yarn
        uses: actions/setup-node@v4
        with:
          node-version: '16'
          registry-url: 'https://registry.yarnpkg.com'

      - name: Install dependencies and Build static generation
        run: |
          yarn
          npm run build
        working-directory: .

      - name: Build and Deploy Firebase Function
        run: |
          yarn global add firebase-tools
          cd functions
          yarn install
          yarn run build
          firebase deploy --only functions --project newcandv2
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        working-directory: functions

      - name: ESLint Check
        run:  yarn lint --quiet || true
        continue-on-error: true
