name: Firebase CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
        env:
          NODE_OPTIONS: --max-old-space-size=4196    # Set the desired memory size in megabytes
    
      - name: npm install, build and test
        run: |
          yarn
          npm run build
      - name: Archive Build
        uses: actions/upload-artifact@v2
        with:
          name: build
          path: build
  deploy: 
      name: Deploy
      needs: build
      runs-on: ubuntu-latest

      steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download Build
        uses: actions/download-artifact@v2
        with:
          name: build
          path: build

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install Firebase Tools
        run: npm install -g firebase-tools

      - name: Deploy to Firebase
        run: firebase deploy -P production --token ${{ secrets.FIREBASE_TOKEN }}

