name: Firebase Function Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install -g yarn

      - name: Install dependencies and Build static generation
        run: |
          yarn
          npm run build
        working-directory: .


      - name: Build and Deploy Firebase Function
        run: |
          npm install -g firebase-tools
          cd functions
          npm install
          npm run build
          firebase deploy --only functions --project newcandv2
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}

